### ISSUE TITLE
[Bug] Interface won't load in Safari

### ISSUE THREAD

**Issue by Teggles** [jlesage/docker-filezilla#51] opened 2023-09-18 20:16 UTC
### Current Behavior

The GUI works fine in Chrome on my Mac, but when I try to load it in Safari, it says:

Unexpected error encountered:

SyntaxError: Unexpected end of script
http://192.168.1.3:7809/core/des.js:265:0

### Expected Behavior

It worked fine in Safari until not long ago.

### Environment

- OS:OSX
- OS version:13.5.2 (latest Ventura)
- CPU:M1
- Docker version: 20.10.24
- Device model: MacBook Pro
- Browser/OS: 16.6

### Container creation

Unraid wizard

### Container log

```text
[xvnc        ] Mon Sep 18 13:06:36 2023
[xvnc        ]  Connections: accepted: /tmp/vnc.sock
[xvnc        ]  SConnection: Client needs protocol version 3.8
[xvnc        ]  SConnection: Client requests security type None(1)
[xvnc        ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc        ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
```

### Container inspect

```text
Not running
```

**Comment by jlesage** [comment] 2023-09-19 12:13
It should work fine in Safari.  This kind of issue is usually caused by a browser plugin.  Do you have ones installed ?

**Comment by jlesage** [comment] 2023-11-02 20:01
Do you have any update on this ?

**Comment by jlesage** [comment] 2023-12-21 17:22
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-12-21 17:22 UTC
Labels: bug
